name: masterpost
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  mask_text_input_formatter: ^1.0.4
  flutter_rating_bar: ^3.2.0+1
  provider: 4.3.3
  share_plus: ^4.0.4
  dio: ^4.0.1
  crop: ^0.5.1+1





  nb_utils: ^4.2.2
  google_fonts: ^2.0.0
  url_launcher: ^6.0.2
  mobx: 1.2.1+4
  flutter_mobx: ^1.0.0
  share: ^2.0.1
  package_info: ^2.0.0
  cached_network_image: ^3.0.0
  http: ^0.13.1

  firebase_core: ^1.0.4
  firebase_auth: ^3.1.4
  cloud_firestore: ^2.5.4
  firebase_crashlytics: ^2.0.1

  glass_kit: ^2.0.0

  permission_handler: ^6.1.3
  path_provider: ^2.0.1

  zoom_widget: ^0.1.3
  screenshot: ^0.3.0
  photo_view: ^0.13.0
  image: ^3.0.8
  flutter_image_compress: ^1.0.0
  image_cropper: ^1.4.0

  image_picker: ^0.7.2+1

  font_awesome_flutter: ^9.0.0
  flutter_vector_icons: ^1.0.0
  flutter_native_image: ^0.0.6
  carousel_slider: ^3.0.0
  velocity_x: 3.3.0
  line_icons: ^2.0.1
  uuid: ^3.0.5
  pay: ^1.0.11
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.5
  mobx_codegen: ^1.1.2
  #flutter packages pub run build_runner build --delete-conflicting-outputs
  flutter_launcher_icons: 0.9.2
  firebase_storage: ^10.2.0


flutter_icons:
  android: true
  ios: true
  image_path: "images/logo.png"
flutter:
  uses-material-design: true
  assets:
    - images/
    - images/import/
    - images/stickers/
    - assets/fonts/
    - assets/

  fonts:
    - family: Neon
      fonts:
        - asset: assets/fonts/neon.ttf
    - family: NeonCity
      fonts:
        - asset: assets/fonts/neoncity.otf
    - family: NeonLights
      fonts:
        - asset: assets/fonts/neonlights.ttf